# Generated by Django 6.0 on 2025-12-15 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(choices=[('CS', 'Corte Suprema'), ('CA', 'Corte de Apelaciones'), ('C', 'Civil'), ('F', 'Familia'), ('P', 'Penal'), ('L', 'Laboral'), ('CO', 'Cobranza')], max_length=2)),
                ('corte', models.CharField(blank=True, help_text='Solo para causas que no sean de Corte Suprema', max_length=100)),
                ('tribunal', models.CharField(max_length=150)),
                ('tipo_causa', models.CharField(help_text='Letra del rol de la causa (Ej: C, R, T, etc.)', max_length=5)),
                ('rol', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('ARC', 'Archivada'), ('NOA', 'No activa')], default='ACT', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causas', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-anio', 'tipo_causa', 'rol'],
                'unique_together': {('tipo_causa', 'rol', 'anio', 'tribunal')},
            },
        ),
    ]
